test:
  adapter:  sqlite3
  database: db/test_database.sqlite3

development:
  adapter:  sqlite3
  database: db/development_database.sqlite3

staging:
  adapter:  sqlite3
  database: db/staging_database.sqlite3

production:
  adapter:  mysql2
  database: code_test_production
  encoding: utf8
  pool:     5
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
